
deck_guess = {
    'Jeskai Saheeli': {'Saheeli Rai': 4, 'Felidar Guardian': 4, 'Fumigate': 1},
    '4C Saheeli': {'Saheeli Rai': 4, 'Felidar Guardian': 4, 'Servant of the Conduit': 4, 'Rogue Refiner': 4},
    'UW Panharmonicon': {'Panharmonicon':4, 'Cloudblazer':4, 'Glint-Nest Crane':4, 'Eldrazi Displacer':4, 'Drowner of Hope':2},
    'UW Control': {'Torrential Gearhulk':4, 'Glimmer of Genius':4,
                   'Immolating Glare':2, 'Blessed Alliance':2, 'Prairie Stream':4},
    'UB Control': {'Torrential Gearhulk':4, 'Glimmer of Genius':4,
                   'Grasp of Darkness':4,
                   'Liliana, the Last Hope':4, 'Sunken Hollow':4,},
    'UR Control': {'Torrential Gearhulk':2, 'Glimmer of Genius':4,
                   'Harnessed Lightning':4, 'Spirebluff Canal':4, 'Wandering Fumarole':4,
                   'Void Shatter':4, 'Anticipate':4, 'Negate':4, 'Galvanic Bombardment':4, 'Dynavolt Tower':1},
    'Jeskai Control': {'Torrential Gearhulk':2, 'Glimmer of Genius':4,
                       'Blessed Alliance':2, 'Port Town':2, 'Stasis Snare':2, 'Radiant Flames':4,
                       'Fumigate':2,
                       'Harnessed Lightning':4, 'Spirebluff Canal':4, 'Wandering Fumarole':4,
                       'Void Shatter':4, 'Anticipate':4, 'Negate':4, 'Galvanic Bombardment':4},
    'UR Spells': {'Lightning Axe':4, 'Tormenting Voice':4, 'Highland Lake':4, 'Spirebluff Canal':4, 'Thermo-Alchemist':4,
                  'Stormchaser Mage':4, 'Galvanic Bombardment':4, 'Collective Defiance':4, 'Fiery Temper':4, 'Thing in the Ice':2},
    #'RB Aggro': {'Fiery Temper':4, 'Bomat Courier':4, 'Unlicensed Disintegration':4,
    #             "Smuggler's Copter":4},
    'RG Energy Aggro': {'Servant of the Conduit':4, 'Attune with Aether':4,
                        'Longtusk Cub':4, 'Voltaic Brawler':4,
                        'Bristling Hydra':4},
    'Grixis Graveyard Emerge': {'Elder Deep-Fiend':4, "Kozilek's Return":4,
                                "Prized Amalgam":4, "Cathartic Reunion":4,
                                "Haunted Dead":4, "Wretched Gryff":1},
    'BG Counters': {'Verdurous Gearhulk':4, 'Rishkar, Peema Renegade': 4, 'Winding Constrictor': 4},
    'GW Tokens': {'Gideon, Ally of Zendikar':4, 'Nissa, Voice of Zendikar':4, 'Archangel Avacyn': 4, },
    'Mardu Vehicle Aggro': {"Cultivator's Caravan":3, "Concealed Courtyard":4,
                            "Scrapheap Scrounger":4, "Heart of Kiran":4,
                            "Veteran Motorist":4,
                            "Unlicensed Disintegration": 4,
                            "Aethersphere Harvester": 1,
                            "Fatal Push": 4,
                            "Inspiring Vantage":4, "Toolcraft Exemplar":4,
                            "Thraben Inspector":4},
    #'BG Delirium Control': {"Liliana, the Last Hope":4, 'Grim Flayer':4,
    #                        'Ishkanah, Grafwidow':4,
    #                        'Grasp of Darkness':4, 'Vessel of Nascency':4,
    #                        'Emrakul, the Promised End': 2,
    #                        'Grapple with the Past': 4,
    #                        "Pilgrim's Eye":1,
    #                        'Noxious Gearhulk':1, 'Ruinous Path':1},
    #'BG Delirium Aggro': {"Smuggler's Copter":4, 'Grim Flayer':4,
    #                      'Ishkanah, Grafwidow':4,
    #                      "Liliana, the Last Hope":4,
    #                      'Grasp of Darkness':4, 'Gnarlwood Dryad':4,
    #                      'Sylvan Advocate': 2,
    #                      'Dead Weight':2,
    #                      'Scrapheap Scrounger':2,
    #                      'Mindwrack Demon':2,
    #                      'Tireless Tracker':2,
    #                      'Hissing Quagmire':2,
    #                      'Verdurous Gearhulk':2,
    #                      'Blossoming Defense':2,
    #                      'Noose Constrictor':2,
    #                     },
    #'UW Flash': {'Reflector Mage':4, "Gideon, Ally of Zendikar":4,
    #             "Smuggler's Copter":4, "Thraben Inspector":4,
    #             "Prairie Stream":4},
    #'RW Vehicle Aggro': {"Smuggler's Copter":4, "Inspiring Vantage":4,
    #                     "Pia Nalaar":4, "Toolcraft Exemplar":4,
    #                     "Selfless Spirit": 4,
    #                     "Declaration in Stone":4,
    #                     "Veteran Motorist":4,
    #                     "Thraben Inspector":4},
    #'RG Aetherworks Marvel': {'Aetherworks Marvel':4, 'Emrakul, the Promised End':4, 'Ulamog, the Ceaseless Hunger':2,
    #                          'Harnessed Lightning':4, 'Attune with Aether':4, 'Vessel of Nascency':4,
    #                          'Forest':8, 'Mountain':4, 'Game Trail':4,
    #                          "Woodweaver's Puzzleknot":4,
    #                         },
    #'Temur Aetherworks Marvel': {'Aetherworks Marvel':4, 'Emrakul, the Promised End':4, 'Ulamog, the Ceaseless Hunger':2,
    #                             'Whirler Virtuoso': 4, 'Botanical Sanctum': 3, 'Spirebluff Canal': 3,
    #                             'Harnessed Lightning':4, 'Attune with Aether':4, 'Vessel of Nascency':4,
    #                             'Island':1, 'Forest': 5, 'Mountain':2,
    #                             "Woodweaver's Puzzleknot":4,
    #                             #"Confiscation Coup":1,
    #                             "Evolving Wilds":1,
    #                         },
    #'BG Aetherworks Marvel': {'Aetherworks Marvel':4, 'Emrakul, the Promised End':4, 'Ulamog, the Ceaseless Hunger':2,
    #                          'Attune with Aether':4, 'Vessel of Nascency':4,
    #                          'Forest':8, 'Swamp':4,
    #                          'To the Slaughter':2, 'Noxious Gearhulk':2, 'Grasp of Darkness':2, 'Blooming Marsh':2,
    #                          "Servant of the Conduit":2,
    #                          "Woodweaver's Puzzleknot":4,
    #                         },
    'Bux Graveyard': {'Haunted Dead':4, 'Prized Amalgam':4, 'Voldaren Pariah':4, 'Cryptbreaker':4,
                     },
    #'Metalwork Colossus': {'Metalwork Colossus':4,
    #                       'Glint-Nest Crane':4,
    #                       'Sanctum of Ugin':4,
    #                       "Inventors' Fair":4,
    #                       "Metalspinner's Puzzleknot":4,
    #                       "Hedron Archive":4,
    #                       "Skysovereign, Consul Flagship":1,
    #                       "Foundry Inspector":2,
    #                       "Spatial Contortion":2,
    #                       "Cultivator's Caravan":2,
    #                       "Elder Deep-Fiend":2,
    #                       "Prophetic Prism":4,
    #                      },
    'BW': {"Ayli, Eternal Pilgrim": 4, "Shambling Vent":4, "Forsaken Sanctuary": 2, "Concealed Courtyard": 4,},
    'Mardu Control': {'Liliana, the Last Hope':4, 'Mountain':4, 'Swamp':4, 'Smoldering Marsh':2, 'Kalitas, Traitor of Ghet':2,
                      'Noxious Gearhulk':2, 'Goblin Dark-Dwellers':2, 'Nahiri, the Harbinger':2, 'Grasp of Darkness':2,
                      'Chandra, Torch of Defiance':2, 'Ruinous Path':2,},
}
